feat(13111): Add plugin workflow
shopwareLabs/SwagMigration pull request #45
Opened 2023-07-04 13:02 UTC by rathmerdominik

2023-07-04 14:26 UTC, mitelg requested changes

2023-07-04 14:26 UTC, mitelg commented on .github/workflows/call-plugin-workflow.yml
> +        name: Analyse PHP Code for SwagUserPrice
```suggestion
        name: Analyse PHP Code for SwagMigration
```

2023-07-04 14:26 UTC, mitelg commented on .github/workflows/call-plugin-workflow.yml
> +        name: Analyse Javascript Code for SwagUserPrice
```suggestion
        name: Analyse Javascript Code for SwagMigration
```

2023-07-05 06:44 UTC, ennasus4sun approved these changes

2023-07-05 09:04 UTC, mitelg approved these changes

2023-07-05 09:05 UTC, merged